### ISSUE TITLE
Missing data reports

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/7-12_issues#1]
Prepare missing data reports for Mamlatdars to work
Like missing year or missing survey numbers. This way we can check the quality of data entry too.

I have the following errors in mind.
1. Some years are missing in between e.g. 1951-1962 for most of the numbers and 1975-1985 for most numbers, but 1962-1975 are not seen in any survey number (That is because the operator missed / didn't get the bunch of 7-12 of that period to scan.
2. When there are two different filenames, but binary files are the same (Error in renaming the file)
3. For a given time period let's say 1975-1985, list the survey numbers which are missing. (This may be because of non separation of pages while scanning / unintentional skipping etc)

Whatever data is already in database, run this query once and generate reports for Mamlatdars / operators to feed correct data.

From next time, please give this at the time of closing. When Mamlatdar closes a village, run these tests and give him error list for correction. When he manually verifies and corrects these errors, then only village should be allowed to be closed. This way we can ensure the data correctness before closure of a village.

**Comment by sandipgoswami** [comment]
![in missing smaple two](https://cloud.githubusercontent.com/assets/18166554/14350785/0b39fa7a-fce9-11e5-8829-9b16ceaea55c.png)
![in missing survey no sample 1](https://cloud.githubusercontent.com/assets/18166554/14350787/0b5ed674-fce9-11e5-807a-4c901c730f71.png)
![in our record](https://cloud.githubusercontent.com/assets/18166554/14350786/0b55db82-fce9-11e5-84cb-2ed71dd5f818.png)

**Comment by sandipgoswami** [comment]
Sir There are so many survey Number village wise missing and i provide missing information without  storing information in our database.

**Comment by sandipgoswami** [comment]
[ANAND-Boriavi Missing Sample.pdf](https://github.com/drdhaval2785/7-12_issues/files/212809/ANAND-Boriavi.Missing.Sample.pdf)
Sir this sample report for Boriavi Village only first five pages

**Comment by sandipgoswami** [comment]
[PELTAD-Ramodadi Missing.pdf](https://github.com/drdhaval2785/7-12_issues/files/212817/PELTAD-Ramodadi.Missing.pdf)

**Comment by drdhaval2785** [comment]
Can't we give it sorted in 
(1) Yearwise
(2) Survey numberwise ?
It would be much easier for them.

**Comment by sandipgoswami** [comment]
yes Sir Year wise possible

**Comment by drdhaval2785** [comment]
OK.
