### ISSUE TITLE
s.no not in our database

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/7-12_issues#13]
If a survey number is not in our database, let a new number be generated provided the initial string is not > 5000. Keep a separate tag that this is added by user.

After the village is completed, if a survey number is found  which is very different e.g. the village had only 2000 survey number and the entered one is 200001, give this in the error reports for the user to verify.

**Comment by drdhaval2785** [comment]
SNC wrote a letter to NIC to provide the web service.
Kindly get in touch with NIC state HQ for the necessary service - technical details.

**Comment by sandipgoswami** [comment]
Sir, Sharma Sir talked with LRC project coordinator Amit Shah so many times. He put this question to  in his meeting also on 26/04/2016 & 27/04/2016.  Copy of SMC letter is mail to Amit Shah & SIO by Sharma Sir with copy to you. NIC GJSC  has got request from SMC. They are in process to take decision
