### ISSUE TITLE
Small numbers in a given year

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/7-12_issues#14]
There are some cases where 1994-1998  -> Only one entry in a given year batch.
They are suspect.

We need to keep single digit ones in suspect list and
If the highest in a given year group increases 1000 -> then double digit are also in suspect list.

**Comment by drdhaval2785** [comment]
As we have decided to give missing years for all survey numbers, this would be redundant.
Closing this issue.

**Comment by sandipgoswami** [comment]
Sir I will try to find out solution for this one
