### ISSUE TITLE
joint survey numbers

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/7-12_issues#2]
Prepare list of survey numbers which have '+' sign in them. They are ekatra karel numbers e.g. 112+113. In such cases, we should display old 7-12 of s.no 112 and 113 both, because 112+113 is joint number of earlier 112 and 113.

**Comment by sandipgoswami** [comment]
![screenshot-localhost 2016-05-04 14-16-24](https://cloud.githubusercontent.com/assets/18166554/15009235/00bce394-1203-11e6-9583-10ea090cc337.png)
![screenshot-localhost 2016-05-04 14-16-56](https://cloud.githubusercontent.com/assets/18166554/15009236/00c3dabe-1203-11e6-9c76-9e4887c83936.png)
![screenshot-localhost 2016-05-04 14-18-26](https://cloud.githubusercontent.com/assets/18166554/15009291/327039fe-1203-11e6-9390-61f5c19374e6.png)
