### ISSUE TITLE
Decrease print area

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/7-12_issues#4]
Slightly decrease the size of print area. Right now the print almost fills the whole page. Shrink it to 90%. Then we will have margin header footer everywhere.

**Comment by sandipgoswami** [comment]
[PrintFile1.pdf](https://github.com/drdhaval2785/7-12_issues/files/217052/PrintFile1.pdf)

**Comment by drdhaval2785** [comment]
Seems OK.
If this result is consistent across different PDFs, we can close this issue.

**Comment by sandipgoswami** [comment]
Sir it is in testing phase so  no error will be come then i will close it

**Comment by drdhaval2785** [comment]
OK
