### ISSUE TITLE
Utility to check unique number

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/7-12_issues#5]
Give a utility to verify whether a given 7-12 with given unique number was issued from a mamlatdar office and when? So that banks or revenue officers can verify that the 7-12 is genuine.

Also write a line at the bottom of ૭-૧૨ print that
'આ ૭-૧૨ મામલતદાર કચેરીથી ઇશ્યુ થયેલ છે કે કેમ તે ચકાસવા ઇચ્છતા હોવ તો ઉપરનો નંબર _______ (weblink) માં નાખી ચકાસણી કરી શકશો'.

**Comment by sandipgoswami** [comment]
Sir any one can check or only authorized  user can check ?

**Comment by sandipgoswami** [comment]
[Verify Screen Shot.pdf](https://github.com/drdhaval2785/7-12_issues/files/195457/Verify.Screen.Shot.pdf)

**Comment by drdhaval2785** [comment]
Anyone can check.
This will work as authentication tool.
Anyone - revenue / police / bank / laymen can test whether the PDF was generate from our service or just faked up.
This can even be on open domain, rather than restricted access.
