### ISSUE TITLE
Update survey number systematically

### ISSUE THREAD

**Issue by drdhaval2785** [drdhaval2785/7-12_issues#6]
Prepare a cron job - take the existing 7-12 numbers from edhara database and regenerate the links to PDF on maybe weekly or monthly basis. E.g. when we took the data from edhara database, there was only s.no 72 and it linked to PDF of s.no 72. Yesterday a sale took place and now the numbers are 72/1 and 72/2. Both of these numbers should be updated in our dropdown list and also show PDF links to s.no 72.

**Comment by drdhaval2785** [comment]
Send a mail to State NIC regarding this web service.

**Comment by sandipgoswami** [comment]
sir already sent last week but no reply from them

**Comment by sandipgoswami** [comment]
We sent a mail on 7/4/2016 to NIC project coordinator, as per telephonic talk with him yesterday, he told that they can provide web service on the request from Revenue Dept / SMC Gandhinagar. So today we will request the same to SMC by your email account.
